name: RustBuildSystem
version: ${project.version}
main: dev.lightdream.rustbuildsystem.Main
authors: [ L1ghtDream ]
website: https://lightdream.dev
depend:
  - LightDreamAPI
commands:
  rbs:
    description: NA