name: RustBuildSystem
version: ${project.version}
main: dev.lightdream.rustbuildsystem.Main
authors: [ L1ghtDream ]
website: https://lightdream.dev
softdepend:
  - LightDreamAPI
commands:
  rbs:
    description: NA
  ld-api:
    description: NA